# ----------------------------------------------------
# 1. Entidad: Documentación General (Raíz)
# ----------------------------------------------------
apiVersion: backstage.io/v1alpha1
kind: Component  # <-- CAMBIO CLAVE AQUÍ
metadata:
  name: documentacion-plataforma-general 
  # ... resto de metadata ...
spec:
  type: documentation # <--- Usa 'type' para clasificarlo
  lifecycle: production
  # ... resto de spec ...

---
# ----------------------------------------------------
# 2. Entidad: Documentación Privada (Hija/Relacionada)
# ----------------------------------------------------
apiVersion: backstage.io/v1alpha1
kind: Component  # <-- CAMBIO CLAVE AQUÍ
metadata:
  name: documentacion-plataforma-interna 
  # ... resto de metadata ...
spec:
  type: documentation # <--- Usa 'type' para clasificarlo
  lifecycle: production
  # ... resto de spec ...
  dependsOn:
    - kind: Component # Asegúrate de que el kind en dependsOn también cambie
      name: documentacion-plataforma-general