# catalog-info.yaml
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: documentacion-plataforma-general 
  description: La documentación técnica de la plataforma general de la empresa.
  tags:
    - docs
    - mkdocs
    - plataforma
  annotations:
    # Si tu catalog-info.yaml estuviera en el mismo repo, usarías:
    backstage.io/techdocs-ref: dir:.

spec:
  type: documentation # Correcto. Categoriza esta entidad como documentación.
  lifecycle: production
  owner: saul-salesa-ntt